modules/routes.py
# modules/routes.py
import requests, html, os, re, shutil, os, requests


from config import Config
from flask import Flask, render_template, flash, redirect, url_for, request, Blueprint, jsonify, session, abort, current_app, send_from_directory, send_file, make_response
from flask import copy_current_request_context, g
from flask_login import current_user, login_user, logout_user, login_required
from flask_wtf import FlaskForm, Form
from flask_mail import Message as MailMessage
from wtforms.validators import DataRequired, Email, Length
from sqlalchemy.exc import IntegrityError, OperationalError, SQLAlchemyError
from sqlalchemy.orm import joinedload
from sqlalchemy import func, Integer, Text, case
from werkzeug.urls import url_parse
from werkzeug.utils import secure_filename
from PIL import Image
from io import BytesIO
from werkzeug.security import generate_password_hash, check_password_hash
from modules import db, mail, cache, limiter
from functools import wraps
from uuid import uuid4
from datetime import datetime, timedelta, timezone
from PIL import Image as PILImage
from PIL import ImageOps
from itsdangerous import URLSafeTimedSerializer
from authlib.jose import jwt
from urllib.parse import unquote

from modules.forms import (
    RSSConfigForm, FlagSubmissionForm, ChallengeSubmissionForm,
    QuizForm, QuestionForm, FlagForm, CourseForm, ThemeUploadForm, UserThemePreferencesForm
)

from modules.models import (
    User, Whitelist, UserPreference, GlobalSettings, Lab, Challenge, Host, RSSConfig,
    Flag, FlagsObtained, ChallengesObtained, Quiz, Question, UserQuizProgress, UserQuestionProgress, Course,
    SystemMessage, message_read_status, HostReview
)
from modules.utilities import admin_required
from feedgen.feed import FeedGenerator
from modules.azure_utils import check_azure_authentication
from modules.theme_manager import ThemeManager
import logging

bp = Blueprint('main', __name__)




s = URLSafeTimedSerializer('YMecr3tK?IzzsSa@e!Zithpze') 
has_initialized_whitelist = False
has_upgraded_admin = False
has_initialized_setup = False
from modules.globals import app_start_time, app_version


@bp.before_app_request
def initial_setup():
    global has_initialized_setup
    if has_initialized_setup:
        return
    has_initialized_setup = True
    app_start_time = datetime.now()  # Record the startup time

    # Initialize whitelist
    try:
        if not Whitelist.query.first():
            default_email = Config.INITIAL_WHITELIST
            default_whitelist = Whitelist(email=default_email)
            db.session.add(default_whitelist)
            db.session.commit()
            print("Default email added to Whitelist.")
    except IntegrityError:
        db.session.rollback()
        print('Default email already exists in Whitelist.')
    except SQLAlchemyError as e:
        db.session.rollback()
        print(f'error adding default email to Whitelist: {e}')

    # Upgrade first user to admin
    try:
        user = User.query.get(1)
        if user and user.role != 'admin':
            user.role = 'admin'
            user.is_email_verified = True
            db.session.commit()
            print(f"User '{user.name}' (ID: 1) upgraded to admin.")
        elif not user:
            print("No user with ID 1 found in the database.")
        else:
            print("User with ID 1 already has admin role.")
    except IntegrityError:
        db.session.rollback()
        print('error while trying to upgrade user to admin.')
    except SQLAlchemyError as e:
        db.session.rollback()
        print(f'error upgrading user to admin: {e}')


@bp.before_request
def check_maintenance_mode():
    settings_record = GlobalSettings.query.first()
    if settings_record and settings_record.settings.get('enableMaintenanceMode', False):
        if not current_user.is_authenticated or current_user.role != 'admin':
            if request.path.startswith('/ctf'):
                return render_template('maintenance.html'), 503

@bp.context_processor
@cache.cached(timeout=500, key_prefix='global_settings')
def inject_settings():
    settings_record = GlobalSettings.query.first()
    if settings_record:
        # Fetch existing settings
        show_logo = settings_record.settings.get('showSystemLogo', False)
        show_help_button = settings_record.settings.get('showHelpButton', False)
        enable_web_links = settings_record.settings.get('enableWebLinksOnDetailsPage', False)
        enable_server_status = settings_record.settings.get('enableServerStatusFeature', False)
        enable_newsletter = settings_record.settings.get('enableNewsletterFeature', False)
        enable_maintenance_mode = settings_record.settings.get('enableMaintenanceMode', False)
    else:
        # Default values if no settings_record is found
        show_logo = True
        show_help_button = True
        enable_web_links = True
        enable_server_status = True
        enable_newsletter = True
        enable_maintenance_mode = False

    return dict(
        show_logo=show_logo, 
        show_help_button=show_help_button, 
        enable_web_links=enable_web_links,
        enable_server_status=enable_server_status,
        enable_newsletter=enable_newsletter,
        enable_maintenance_mode=enable_maintenance_mode
    )

@bp.context_processor
def utility_processor():
    return dict(datetime=datetime)


@bp.route('/ctf')
def ctf_home():
    return render_template('site/ctf.html')


@bp.route('/ctf/leaderboard')
def leaderboard():
    # Fetch user scores from the database
    print("Fetching user scores from the database...")
    users = User.query.all()
    
    # Prepare user data for the template
    user_data = []
    for user in users:
        total_score = user.calculate_total_score()
        user_data.append({
            'id': user.id,
            'name': user.name,
            'score_total': total_score,
            'avatarpath': user.avatarpath
        })
    
    # Sort users by total score
    user_data.sort(key=lambda x: x['score_total'], reverse=True)
    
    # Debug print to verify fetched data
    if user_data:
        print(f"Users: {user_data}")

    return render_template('site/leaderboard.html', users=user_data)



@bp.route('/ctf/test_quiz/<int:quiz_id>', methods=['GET', 'POST'])
@login_required
@admin_required
def test_quiz(quiz_id):
    quiz = Quiz.query.get_or_404(quiz_id)
    questions = Question.query.filter_by(quiz_id=quiz_id).order_by(Question.id).all()
    
    if 'current_question' not in session:
        session['current_question'] = 0
        session['results'] = []
        session['total_score'] = 0
    
    if request.method == 'POST':
        answer = request.form.get('answer')
        current_question = questions[session['current_question']]
        is_correct = answer == current_question.correct_answer
        if is_correct:
            session['total_score'] += current_question.points
        session['results'].append({
            'question': current_question.question_text,
            'user_answer': answer,
            'correct_answer': current_question.correct_answer,
            'is_correct': is_correct,
            'explanation': current_question.explanation
        })
        session['current_question'] += 1
        session.modified = True
        
        if session['current_question'] >= len(questions):
            results = session['results']
            total_score = session['total_score']
            session.pop('current_question', None)
            session.pop('results', None)
            session.pop('total_score', None)
            return render_template('site/test_quiz_results.html', quiz=quiz, results=results, total_score=total_score)
    
    if session['current_question'] < len(questions):
        question = questions[session['current_question']]
        return render_template('site/test_quiz.html', quiz=quiz, question=question, progress=session['current_question']+1, total=len(questions))
    
    # This should not happen, but just in case
    return redirect(url_for('main.quizzes'))


@bp.route('/ctf/challenges')
def challenges():
    # Fetch challenges from the database
    challenges = Challenge.query.all()
    for challenge in challenges:
        if challenge.html_link:
            challenge.image = challenge.html_link
        else:
            challenge.image = 'default_challenge_image.jpg'
        
        # Check if the user has already completed or used a hint for this challenge
        if current_user.is_authenticated:
            challenge_obtained = ChallengesObtained.query.filter_by(
                user_id=current_user.id, 
                challenge_id=challenge.id
            ).first()
            if challenge_obtained:
                challenge.completed = challenge_obtained.completed
                challenge.hint_used = challenge_obtained.used_hint
                challenge.completed_at = challenge_obtained.completed_at
            else:
                challenge.completed = False
                challenge.hint_used = False
                challenge.completed_at = None
        else:
            challenge.completed = False
            challenge.hint_used = False
            challenge.completed_at = None

    form = ChallengeSubmissionForm()
    return render_template('site/challenges.html', challenges=challenges, form=form)

@bp.route('/get_hint/<int:challenge_id>', methods=['POST'])
@login_required
def get_hint(challenge_id):
    try:
        challenge = Challenge.query.get_or_404(challenge_id)
        user_challenge = ChallengesObtained.query.filter_by(user_id=current_user.id, challenge_id=challenge_id).first()
        
        if not user_challenge:
            user_challenge = ChallengesObtained(user_id=current_user.id, challenge_id=challenge_id, used_hint=True)
            db.session.add(user_challenge)
        elif not user_challenge.used_hint:
            user_challenge.used_hint = True
        
        db.session.commit()
        
        
        

modules/templates/site/ctf.html
<!-- /modules/templa    tes/ctf.html -->
{% extends 'base.html' %}

{% block content %}
{% with messages = get_flashed_messages() %}
{% if messages %}
<div>
    {% for message in messages %}
    <div class="alert alert-info" role="alert">{{ message }}</div>
    {% endfor %}
</div>
{% endif %}
{% endwith %}


<link rel="stylesheet" href="/static/css/ctf.css">


<div class="container">
    <div class="glass-panel">
        <div class="hackplanet_titles">
            <h1>HackPlanet.EU Training Grounds</h1>
        </div>

        <div class="row">
            <div class="col-md-6">
                <a href="{{ url_for('main.hacking_labs') }}" class="btn btn-green btn-block">
                    <img src="{{ url_for('static', filename='/newstyle/labs.png') }}" alt="Hacking Labs" class="img-fluid ctf-button-image">
                    <div class="ctf-label">
                        <h2>Hacking Labs</h2>
                    </div>
                </a>
            </div>
            <div class="col-md-6">
                <a href="{{ url_for('main.challenges') }}" class="btn btn-green btn-block">
                    <img src="{{ url_for('static', filename='/newstyle/challenges.png') }}" alt="Challenges" class="img-fluid ctf-button-image">
                    <div class="ctf-label">
                        <h2>Crypto Challenges</h2>
                    </div>
                </a>
            </div>
        </div>
        <div class="row">
            <div class="col-md-6">
                <a href="{{ url_for('main.study_room') }}" class="btn btn-green btn-block">
                    <img src="{{ url_for('static', filename='/newstyle/study.png') }}" alt="Study Room" class="img-fluid ctf-button-image">
                    <div class="ctf-label">
                        <h2>Study Room</h2>
                    </div>
                </a>
            </div>
            <div class="col-md-6">
                <a href="{{ url_for('main.quizzes') }}" class="btn btn-green btn-block">
                    <img src="{{ url_for('static', filename='/newstyle/quiz.png') }}" alt="Quizzes" class="img-fluid ctf-button-image">
                    <div class="ctf-label">
                        <h2>Quizzes</h2>
                    </div>
                </a>
            </div>

        </div>
    </div>
</div>
{% endblock %}

modules/templates/site/hacking_labs.html
{% extends 'base.html' %}

{% block content %}
{% with messages = get_flashed_messages() %}
{% if messages %}
<div>
    {% for message in messages %}
    <div class="alert alert-info" role="alert">{{ message }}</div>
    {% endfor %}
</div>
{% endif %}
{% endwith %}

<div class="container">

    <div class="glass-panel">
        <div class="hackplanet_titles">
            <div class="text-start">
                <a href="{{ url_for('main.ctf_home') }}" class="btn btn-secondary">Back</a>
            </div>
            
            <h1>HackPlanet.EU Hacking Labs</h1>
        </div>

        {% if no_labs %}
            <div class="alert alert-warning" role="alert">
                There are no labs defined. Please ask your administrator to define new labs.
                {% if is_admin %}
                    <a href="{{ url_for('bp_admin.lab_manager') }}" class="btn btn-primary">Go to Lab Manager</a>
                {% endif %}
            </div>
        {% else %}
        {% for lab in labs %}

            <div class="lab">
                <h2>{{ lab.name }}</h2>
            </div>
            <div class="lab-content">
                <div class="lab-description">
                    <p>{{ lab.description }}</p>
                    <p>VPN Status: <span class="vpn-status-indicator" data-agent-id="{{ lab.vpn_server }}">Loading...</span></p>
                    {% if lab.vpn_server %}
                        <button class="btn btn-success start-vpn" data-lab-id="{{ lab.id }}">Start VPN</button>
                        <button class="btn btn-danger stop-vpn" data-lab-id="{{ lab.id }}">Stop VPN</button>
                    {% endif %}
                    {% if lab.vpn_file %}
                        <a href="{{ '/static/library/labfiles/' + lab.vpn_file }}" class="download-button btn btn-primary">Download VPN Access</a>
                    {% endif %}
                </div>
                <div class="lab-image-container">
                    {% if lab.image %}
                    <img src="{{ url_for('static', filename='library/images/labs/' + lab.image) }}" alt="{{ lab.name }}" class="lab-image">
                    {% endif %}
                </div>
            </div>
                <script>
                    const labVpnServer = "{{ lab.vpn_server }}"
                </script>   
            </div>
            <div class="hosts">
                {% if lab in labs_without_hosts %}
                    <div class="alert alert-warning" role="alert">
                        There are no hosts defined for this lab.
                        {% if is_admin %}
                            <a href="{{ url_for('bp_admin.host_editor') }}" class="btn btn-primary">Add Host</a>
                        {% endif %}
                    </div>
                {% else %}
                    {% for host in lab.hosts %}
                    <div class="host" data-host-id="{{ host.id }}">
                        <h3>{{ host.name | upper }} </h3>
                        <div class="host-image-container">
                            <img src="{{ '/static/library/images/hosts/' + host.image_url }}" alt="{{ host.name }}" class="host-image">
                        </div>
                        <p>IP Address: {{ host.ip }}</p>
                        
                        <!-- Add ratings display -->
                        <div class="host-ratings">
                            <p>Ratings: 
                                <span class="stars" data-rating="{{ host.overall_rating }}"></span> 
                                ({{ host.overall_rating }}) <small>{{ host.review_count }} review(s)</small>
                            </p>
                        </div>
                        <p>Difficulty: {{ host.difficulty }} {% if host.difficulty == 1 %}?{% elif host.difficulty == 2 %}?{% elif host.difficulty == 3 %}?{% elif host.difficulty == 4 %}?{% elif host.difficulty == 5 %}?{% elif host.difficulty == 6 %}?{% elif host.difficulty == 7 %}?{% elif host.difficulty == 8 %}?{% elif host.difficulty == 9 %}?{% elif host.difficulty == 10 %}?{% endif %}</p>
                        <p>Status: <span class="status-indicator" data-agent-id="{{ host.name }}">Loading...</span></p>
                        <a href="{{ url_for('main.host_details', host_id=host.id) }}" class="btn btn-info">Host Details</a>
    
                        <div class="host-inputarea">
                            {% if host.name != 'kalismurf' %}
                            {% if host.flags %}
                                <div class="flag-input-container">
                                    <input type="text" id="user-flag-{{ host.id }}" placeholder="Enter User Flag" class="flag-input" {% if host.user_flag_completed %}style="display: none;"{% endif %}>
                                    <button type="button" class="btn btn-success" onclick="submitFlag('{{ host.id }}', 'user')" {% if host.user_flag_completed %}disabled{% endif %}>
                                        {% if host.user_flag_completed %}User Flag Hacked{% else %}Submit User Flag{% endif %}
                                    </button>
                                </div>
                                <div class="flag-input-container">
                                    <input type="text" id="root-flag-{{ host.id }}" placeholder="Enter Root Flag" class="flag-input" {% if host.root_flag_completed %}style="display: none;"{% endif %}>
                                    <button type="button" class="btn btn-danger" onclick="submitFlag('{{ host.id }}', 'root')" {% if host.root_flag_completed %}disabled{% endif %}>
                                        {% if host.root_flag_completed %}Root Flag Hacked{% else %}Submit Root Flag{% endif %}
                                    </button>
                                </div>
                                {% if host.user_flag_completed and host.root_flag_completed %}
                                <div class="completed-overlay">PWNED!</div>
                                {% endif %}
                            {% else %}
                                <p>No flags available for this host.</p>
                            {% endif %}
                            {% else %}
                            <div class="kalismurf-credentials">
                                <p>username : kali</p>
                                <p>password : KaliLinux2024!</p>
                            </div>
                            {% endif %}
                        </div>
                    </div>
                    {% endfor %}
                {% endif %}
            </div>
        </div>
        </div>
            {% endfor %}
        {% endif %}
    </div>
</div>

<!-- Flag Submission Modal -->
<div class="modal fade" id="flagModal" tabindex="-1" aria-labelledby="flagModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="flagModalLabel"></h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body" id="flagModalBody">
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>
<script src="{{ url_for('static', filename='js/flag_submission.js') }}"></script>
<script>
    var loops = 0;

    document.addEventListener('DOMContentLoaded', function() {
        function updateHostStatus() {
            console.log('Fetching host status...');
            fetch('/api/host_status')
                .then(response => {
                    if (!response.ok) {
                        throw new Error(`Network response was not ok: ${response.statusText}`);
                    }
                    return response.json();
                })
                .then(data => {
                    // console.log('Received host status data:', data);
                    if (data.hosts) {
                        data.hosts.forEach(host => {
                            // console.log(`Processing host_id: ${host.agent_id}, Status: ${host.status}, Is VPN: ${host.is_vpn}`);
                            const selector = host.is_vpn ? `.vpn-status-indicator[data-agent-id="${host.agent_id}"]` : `.status-indicator[data-agent-id="${host.agent_id}"]`;
                            const statusElement = document.querySelector(selector);
                            if (statusElement) {
                                let status = host.status;
                                let color;
                                switch (status) {
                                    case 'Online':
                                        color = '#28a745';
                                        break;
                                    case 'Offline':
                                        color = '#dc3545';
                                        break;
                                    case 'Unknown':
                                        color = '#ffc107';
                                        break;
                                    default:
                                        status = 'Unknown';
                                        color = '#ffc107';
                                }
                                statusElement.textContent = status;
                                statusElement.style.color = color;
                                console.log(`Updated status for agent_id: ${host.agent_id} to ${status}`);
                                
                                // Update VPN status in the lab section if it's a VPN server
                                if (host.is_vpn) {
                                    const labVpnStatus = document.querySelector(`.lab-vpn-status[data-lab-id="${host.lab_id}"]`);
                                    if (labVpnStatus) {
                                        labVpnStatus.textContent = status;
                                        labVpnStatus.style.color = color;
                                    }
                                }
                            } else {
                                console.warn(`No status element found for agent_id: ${host.agent_id}`);
                            }
                        });
                    } else {
                        console.error('No hosts data found in the response.');
                    }
                })
                .catch(error => {
                    console.error('Error fetching host status:', error);
                });
        }
        
        // Update status immediately and then every 10 seconds
        loops++;
        console.log(`Loop number: ${loops}`);
        updateHostStatus();
        setInterval(updateHostStatus, 10000);
    
        // VPN control functionality
        function manageVPN(labId, action) {
            fetch('/manage_vpn', {
                method: 'POST',
                headers: {
                    'Content-Type': 'application/json',
                    'X-CSRFToken': document.querySelector('meta[name="csrf-token"]').getAttribute('content')
                },
                body: JSON.stringify({ lab_id: labId, action: action })
            })
            .then(response => response.json())
            .then(data => {
                if (data.status === "success") {
                    // console.log(data.message);
                    
                } else {
                    console.error("Error managing VPN:", data.message);
                }
            })
            .catch(error => console.error('Error:', error));
        }
    
        // Listen for clicks on VPN buttons
        document.addEventListener('click', function(event) {
            if (event.target.classList.contains('start-vpn') || event.target.classList.contains('stop-vpn')) {
                // Update the VPN status indicator based on button clicks
                const vpnStatusIndicator = document.querySelector(`.vpn-status-indicator[data-agent-id="${labVpnServer}"]`);
                if (vpnStatusIndicator) {
                    vpnStatusIndicator.textContent = event.target.classList.contains('start-vpn') ? 'Starting' : 'Stopping';
                }
                manageVPN(event.target.dataset.labId, event.target.classList.contains('start-vpn') ? 'start' : 'stop');
            }
        });
    
        // Initialize star ratings when page loads
        initializeStarRatings();
    });
    


</script>

<style>
.stars {
    display: inline-block;
}
.stars i {
    color: #ccc;
    font-size: 16px;
}
.stars i.active {
    color: #FFD700;
}
</style>

{% endblock %}

modules/templates/site/help.html
{% extends 'base.html' %}

{% block content %}
<link rel="stylesheet" href="{{ url_for('static', filename='css/help.css') }}">
{% with messages = get_flashed_messages() %}
{% if messages %}
<div>
    {% for message in messages %}
    <div class="alert alert-info" role="alert">{{ message }}</div>
    {% endfor %}
</div>
{% endif %}
{% endwith %}
<div class="container">

    <div class="glass-panel">
    <div class="row">
        <div class="col-lg-8">
            <div class="card shadow-lg">
                <div class="card-header bg-success text-white">
                    <h2 class="mb-0">HackPlanet.EU Help Center</h2>
                </div>
                <div class="card-body">
                    <h3 class="card-title text-success">Getting Started</h3>
                    <ul class="list-group list-group-flush mb-4">
                        <li class="list-group-item bg-light">Each LAB is a separate network with machines you can hack.</li>
                        <li class="list-group-item bg-light">To access each LAB, download and use the provided OpenVPN connection file.</li>
                        <li class="list-group-item bg-light">Submit flags to check your progress and earn points.</li>
                        <li class="list-group-item bg-light">Check the leaderboards to see how you rank among other participants.</li>
                        <li class="list-group-item bg-light">Manage VMs by starting and stopping them, including the VPN server.</li>
                    </ul>

                    <h3 class="card-title text-success">Rules of Engagement</h3>
                    <ul class="list-group list-group-flush mb-4">
                        <li class="list-group-item bg-light">Brute force password cracking is never the intended solution. You may try, but it's likely not the correct path.</li>
                        <li class="list-group-item bg-light">Do not attack the VPN server or the HackPlanet.eu webserver.</li>
                        <li class="list-group-item bg-light">Do not attack or disrupt other participants.</li>
                        <li class="list-group-item bg-light">Once you gain root access, do not delete flags. Please clean up exploit-related files when finished to prevent spoilers.</li>
                        <li class="list-group-item bg-light">If a host becomes unresponsive, contact support for a reboot/rebuild.</li>
                    </ul>

                    <h3 class="card-title text-success">Technical Details</h3>
                    <ul class="list-group list-group-flush">
                        <li class="list-group-item bg-light">The VPN uses a TUN interface, making it incompatible with nmap under Windows.</li>
                        <li class="list-group-item bg-light">A Kali Linux host is available inside each LAB network for all HackPlanet users.</li>
                        <li class="list-group-item bg-light">The VPN server should always be running if you want to connect to the lab.</li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="col-lg-4">
            <div class="card shadow-lg">
                <div class="card-body">
                    <img src="{{ url_for('static', filename='newstyle/hackplanet_help.jpg') }}" alt="HackPlanet.EU Logo" class="img-fluid rounded">
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

modules/templates/site/quizzes.html
{% extends "base.html" %}
{% block content %}
{% with messages = get_flashed_messages() %}
{% if messages %}
<div>
    {% for message in messages %}
    <div class="alert alert-info" role="alert">{{ message }}</div>
    {% endfor %}
</div>
{% endif %}
{% endwith %}

<div class="container">
    <div class="glass-panel">
        <div class="text-start">
            <a href="{{ url_for('main.ctf_home') }}" class="btn btn-secondary">Back</a>
        </div>
        <h1>Available Quizzes</h1>
        <div class="row">
            {% for quiz in quizzes %}
            <div class="col-md-4 mb-4">
                <div class="card quiz-card">
                    <div class="quiz-image-container">
                        <img src="{{ quiz.image_url }}" class="card-img-top" alt="{{ quiz.title }}">
                        {% if quiz.id in completed_quizzes %}
                            {% if completed_quizzes[quiz.id] >= quiz.min_score %}
                                <div class="quiz-overlay completed"><span>PASSED</span></div>
                            {% else %}
                                <div class="quiz-overlay failed"><span>FAILED</span></div>
                            {% endif %}
                        {% endif %}
                    </div>
                    <div class="card-body">
                        <h5 class="card-title">{{ quiz.title }}</h5>
                        <p class="card-text">{{ quiz.description }}</p>
                        <p class="card-text"><small class="text-muted">Questions: {{ quiz.question_count }} | Max Score: {{ quiz.max_score }}</small></p>
                        {% if quiz.id in completed_quizzes %}
                            {% if completed_quizzes[quiz.id] >= quiz.min_score %}
                                <p class="text-success">Completed - Score: {{ completed_quizzes[quiz.id] }} (Passing score: {{ quiz.min_score }})</p>
                            {% else %}
                                <p class="text-danger">Completed - Score: {{ completed_quizzes[quiz.id] }} (Failed)</p>
                            {% endif %}
                            <a href="{{ url_for('main.quiz_results', quiz_id=quiz.id) }}" class="btn btn-secondary">View Results</a>
                        {% else %}
                            <a href="{{ url_for('main.take_quiz', quiz_id=quiz.id) }}" class="btn btn-primary">Take Quiz</a>
                        {% endif %}
                        {% if current_user.role == 'admin' %}
                            <a href="{{ url_for('main.test_quiz', quiz_id=quiz.id) }}" class="btn btn-warning mt-2">Test Quiz</a>
                        {% endif %}
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</div>
{% endblock %}