modules/routes.py
# modules/routes.py
import requests, html, os, re, shutil, os, requests


from config import Config
from flask import Flask, render_template, flash, redirect, url_for, request, Blueprint, jsonify, session, abort, current_app, send_from_directory, send_file, make_response
from flask import copy_current_request_context, g
from flask_login import current_user, login_user, logout_user, login_required
from flask_wtf import FlaskForm, Form
from flask_mail import Message as MailMessage
from wtforms.validators import DataRequired, Email, Length
from sqlalchemy.exc import IntegrityError, OperationalError, SQLAlchemyError
from sqlalchemy.orm import joinedload
from sqlalchemy import func, Integer, Text, case
from werkzeug.urls import url_parse
from werkzeug.utils import secure_filename
from PIL import Image
from io import BytesIO
from werkzeug.security import generate_password_hash, check_password_hash
from modules import db, mail, cache, limiter
from functools import wraps
from uuid import uuid4
from datetime import datetime, timedelta, timezone
from PIL import Image as PILImage
from PIL import ImageOps
from itsdangerous import URLSafeTimedSerializer
from authlib.jose import jwt
from urllib.parse import unquote

from modules.forms import (
    RSSConfigForm, FlagSubmissionForm, ChallengeSubmissionForm,
    QuizForm, QuestionForm, FlagForm, CourseForm, ThemeUploadForm, UserThemePreferencesForm
)

from modules.models import (
    User, Whitelist, UserPreference, GlobalSettings, Lab, Challenge, Host, RSSConfig,
    Flag, FlagsObtained, ChallengesObtained, Quiz, Question, UserQuizProgress, UserQuestionProgress, Course,
    SystemMessage, message_read_status, HostReview
)
from modules.utilities import admin_required
from feedgen.feed import FeedGenerator
from modules.azure_utils import check_azure_authentication
from modules.theme_manager import ThemeManager
import logging

bp = Blueprint('main', __name__)




s = URLSafeTimedSerializer('YMecr3tK?IzzsSa@e!Zithpze') 
has_initialized_whitelist = False
has_upgraded_admin = False
has_initialized_setup = False
from modules.globals import app_start_time, app_version


@bp.before_app_request
def initial_setup():
    global has_initialized_setup
    if has_initialized_setup:
        return
    has_initialized_setup = True
    app_start_time = datetime.now()  # Record the startup time

    # Initialize whitelist
    try:
        if not Whitelist.query.first():
            default_email = Config.INITIAL_WHITELIST
            default_whitelist = Whitelist(email=default_email)
            db.session.add(default_whitelist)
            db.session.commit()
            print("Default email added to Whitelist.")
    except IntegrityError:
        db.session.rollback()
        print('Default email already exists in Whitelist.')
    except SQLAlchemyError as e:
        db.session.rollback()
        print(f'error adding default email to Whitelist: {e}')

    # Upgrade first user to admin
    try:
        user = User.query.get(1)
        if user and user.role != 'admin':
            user.role = 'admin'
            user.is_email_verified = True
            db.session.commit()
            print(f"User '{user.name}' (ID: 1) upgraded to admin.")
        elif not user:
            print("No user with ID 1 found in the database.")
        else:
            print("User with ID 1 already has admin role.")
    except IntegrityError:
        db.session.rollback()
        print('error while trying to upgrade user to admin.')
    except SQLAlchemyError as e:
        db.session.rollback()
        print(f'error upgrading user to admin: {e}')


@bp.before_request
def check_maintenance_mode():
    settings_record = GlobalSettings.query.first()
    if settings_record and settings_record.settings.get('enableMaintenanceMode', False):
        if not current_user.is_authenticated or current_user.role != 'admin':
            if request.path.startswith('/ctf'):
                return render_template('maintenance.html'), 503

@bp.context_processor
@cache.cached(timeout=500, key_prefix='global_settings')
def inject_settings():
    settings_record = GlobalSettings.query.first()
    if settings_record:
        # Fetch existing settings
        show_logo = settings_record.settings.get('showSystemLogo', False)
        show_help_button = settings_record.settings.get('showHelpButton', False)
        enable_web_links = settings_record.settings.get('enableWebLinksOnDetailsPage', False)
        enable_server_status = settings_record.settings.get('enableServerStatusFeature', False)
        enable_newsletter = settings_record.settings.get('enableNewsletterFeature', False)
        enable_maintenance_mode = settings_record.settings.get('enableMaintenanceMode', False)
    else:
        # Default values if no settings_record is found
        show_logo = True
        show_help_button = True
        enable_web_links = True
        enable_server_status = True
        enable_newsletter = True
        enable_maintenance_mode = False

    return dict(
        show_logo=show_logo, 
        show_help_button=show_help_button, 
        enable_web_links=enable_web_links,
        enable_server_status=enable_server_status,
        enable_newsletter=enable_newsletter,
        enable_maintenance_mode=enable_maintenance_mode
    )

@bp.context_processor
def utility_processor():
    return dict(datetime=datetime)


@bp.route('/ctf')
def ctf_home():
    return render_template('site/ctf.html')


@bp.route('/ctf/leaderboard')
def leaderboard():
    # Fetch user scores from the database
    print("Fetching user scores from the database...")
    users = User.query.all()
    
    # Prepare user data for the template
    user_data = []
    for user in users:
        total_score = user.calculate_total_score()
        user_data.append({
            'id': user.id,
            'name': user.name,
            'score_total': total_score,
            'avatarpath': user.avatarpath
        })
    
    # Sort users by total score
    user_data.sort(key=lambda x: x['score_total'], reverse=True)
    
    # Debug print to verify fetched data
    if user_data:
        print(f"Users: {user_data}")

    return render_template('site/leaderboard.html', users=user_data)



@bp.route('/ctf/test_quiz/<int:quiz_id>', methods=['GET', 'POST'])
@login_required
@admin_required
def test_quiz(quiz_id):
    quiz = Quiz.query.get_or_404(quiz_id)
    questions = Question.query.filter_by(quiz_id=quiz_id).order_by(Question.id).all()
    
    if 'current_question' not in session:
        session['current_question'] = 0
        session['results'] = []
        session['total_score'] = 0
    
    if request.method == 'POST':
        answer = request.form.get('answer')
        current_question = questions[session['current_question']]
        is_correct = answer == current_question.correct_answer
        if is_correct:
            session['total_score'] += current_question.points
        session['results'].append({
            'question': current_question.question_text,
            'user_answer': answer,
            'correct_answer': current_question.correct_answer,
            'is_correct': is_correct,
            'explanation': current_question.explanation
        })
        session['current_question'] += 1
        session.modified = True
        
        if session['current_question'] >= len(questions):
            results = session['results']
            total_score = session['total_score']
            session.pop('current_question', None)
            session.pop('results', None)
            session.pop('total_score', None)
            return render_template('site/test_quiz_results.html', quiz=quiz, results=results, total_score=total_score)
    
    if session['current_question'] < len(questions):
        question = questions[session['current_question']]
        return render_template('site/test_quiz.html', quiz=quiz, question=question, progress=session['current_question']+1, total=len(questions))
    
    # This should not happen, but just in case
    return redirect(url_for('main.quizzes'))


@bp.route('/ctf/challenges')
def challenges():
    # Fetch challenges from the database
    challenges = Challenge.query.all()
    for challenge in challenges:
        if challenge.html_link:
            challenge.image = challenge.html_link
        else:
            challenge.image = 'default_challenge_image.jpg'
        
        # Check if the user has already completed or used a hint for this challenge
        if current_user.is_authenticated:
            challenge_obtained = ChallengesObtained.query.filter_by(
                user_id=current_user.id, 
                challenge_id=challenge.id
            ).first()
            if challenge_obtained:
                challenge.completed = challenge_obtained.completed
                challenge.hint_used = challenge_obtained.used_hint
                challenge.completed_at = challenge_obtained.completed_at
            else:
                challenge.completed = False
                challenge.hint_used = False
                challenge.completed_at = None
        else:
            challenge.completed = False
            challenge.hint_used = False
            challenge.completed_at = None

    form = ChallengeSubmissionForm()
    return render_template('site/challenges.html', challenges=challenges, form=form)

@bp.route('/get_hint/<int:challenge_id>', methods=['POST'])
@login_required
def get_hint(challenge_id):
    try:
        challenge = Challenge.query.get_or_404(challenge_id)
        user_challenge = ChallengesObtained.query.filter_by(user_id=current_user.id, challenge_id=challenge_id).first()
        
        if not user_challenge:
            user_challenge = ChallengesObtained(user_id=current_user.id, challenge_id=challenge_id, used_hint=True)
            db.session.add(user_challenge)
        elif not user_challenge.used_hint:
            user_challenge.used_hint = True
        
        db.session.commit()
        
        
        

modules/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta charset="utf-8">
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <link rel="alternate" type="application/rss+xml" title="System Messages RSS Feed" href="{{ url_for('main.system_messages_feed') }}">

    <title>HackPlanet.EU</title>
    {% block styles %}
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css"/>
    <script src="https://code.jquery.com/jquery-3.7.1.js" integrity="sha256-eKhayi8LEQwp4NKxN+CfCh+3qOVUtJn3QNZ0TciWLP4=" crossorigin="anonymous"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">    
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

    <!-- Always load default theme -->
    <link rel="stylesheet" href="{{ url_for('static', filename='themes/default/css/style.css') }}">
    
    {% if current_theme and current_theme != 'default' %}
    <link rel="stylesheet" href="{{ url_for('static', filename='themes/' + current_theme + '/css/style.css') }}">
    {% endif %}
    {% endblock %}

</head>
<body>




<div id="sidebar" class="sidebar">
    {% if current_user.is_authenticated %}
    <div class="useraccount-minimenu-container">
        <!-- User Account Icon at the Bottom Left -->
        <div id="userAccountIcon" class="user-account-icon">
            {% set thumbnail_path = current_user.avatarpath | replace('.', '_thumbnail.') %}
            <img src="{{ url_for('static', filename=thumbnail_path) }}" alt="User Avatar" class="user-avatar">
            <span class="user-name" style="color: white;">{{ current_user.name | capitalize }}</span>

            <i class="fas fa-chevron-up user-expand-icon" style="color: white;"></i>
        </div>

        <!-- Expandable User Account Menu -->
        <div id="userAccountMenu" class="user-account-menu hide">
            <a href="{{ url_for('main.hacker_profile', user_id=current_user.id) }}" class="account-menu-option">Profile</a>
            
            <a href="{{ url_for('bp_login.invites') }}" class="account-menu-option">Invites</a>
            <a href="{{ url_for('main.user_theme_preferences') }}" class="account-menu-option">Theme</a>
            <a href="{{ url_for('bp_settings.account_pw') }}" class="account-menu-option">Change Password</a>
            <a href="{{ url_for('site.logout') }}" class="account-menu-option">Logout</a>
        </div>
    </div>
    {% endif %}
    <a href="/ctf">
        {% if show_logo %}
            <div class="menu-logo-image {% if enable_maintenance_mode %}maintenance-mode{% endif %}">
                <!-- Your CSS will apply here, displaying the logo -->
            </div>
        {% endif %}
    </a>
    
    
    <div class="sidebar-header">
        <button id="toggleSidebar" class="toggle-sidebar">
            <i class="icon-chevron">&gt;</i>
        </button>
    </div>
    <div class="sidebar-menu">
        {% if current_user.is_authenticated %}
    
            {% if current_user.role == 'admin' %}
            <a href="/admin/dashboard" class="sidebar-link">
                <i class="fas fa-tachometer-alt"></i>
                <span class="link-text">Admin</span>
            </a>
            {% endif %}
    

            <a href="{{ url_for('main.ctf_home') }}" class="sidebar-link">
                <i class="fas fa-skull"></i>
                <span class="link-text">HackPlanet</span>
            </a>

            <a href="{{ url_for('main.hacker_profile', user_id=current_user.id) }}" class="sidebar-link">
                <i class="fas fa-chart-simple"></i>
                <span class="link-text">Profile</span>
            </a>

            <a href="{{ url_for('main.leaderboard') }}" class="sidebar-link">
                <i class="fas fa-trophy"></i>
                <span class="link-text">Leaderboard</span>
            </a>

            <a href="{{ url_for('main.system_messages') }}" class="sidebar-link">
                <i class="fas fa-bell"></i>
                <span class="link-text">Messages</span>
                {% if current_user.is_authenticated %}
                    {% set unread_count = get_unread_message_count() %}
                    {% if unread_count > 0 %}
                        <span id="unreadMessageCount" class="badge bg-danger">{{ unread_count }}</span>
                    {% endif %}
                {% endif %}
            </a>

            {% if current_user.is_authenticated %}
            <a href="{{ url_for('bp_help.help_page') }}" class="sidebar-link">
                <i class="fas fa-question-circle"></i>
                <span class="link-text">Help</span>
            </a>
            {% endif %}
            
        {% else %}
            <a href="{{ url_for('bp_login.login') }}" class="sidebar-link"><i class="fas fa-sign-in-alt"></i><span class="link-text">Login</span></a>
            <a href="{{ url_for('bp_login.register') }}" class="sidebar-link"><i class="fas fa-user-plus"></i><span class="link-text">Register</span></a>
        {% endif %}
     
    </div>
    
</div>
<div id="content">
    {% block content %}{% endblock %}
</div>

<script>
    document.addEventListener("DOMContentLoaded", function() {
        console.log("Document loaded.");

        // Existing function to close all submenus
        function closeAllSubmenus() {
            document.querySelectorAll('.submenu').forEach(submenu => {
                submenu.style.display = 'none';
            });
            document.querySelectorAll('.has-submenu').forEach(item => {
                item.classList.remove('open');
            });
        }
    
        closeAllSubmenus();
    
        // Toggle sidebar
        document.getElementById("toggleSidebar").addEventListener("click", function() {
            console.log("Sidebar toggle clicked.");
            document.getElementById("sidebar").classList.toggle("collapsed");
            document.getElementById("content").classList.toggle("collapsed");
            closeAllSubmenus();
        });
    
        // User account icon click event
        document.getElementById('userAccountIcon').addEventListener('click', function() {
            console.log("User account icon clicked.");

            var menu = document.getElementById('userAccountMenu');
            var icon = document.querySelector('.user-expand-icon');
        
            if (menu.classList.contains('hide')) {
                console.log("Menu is hidden, showing now.");
                menu.classList.remove('hide');
                menu.classList.add('show');
                icon.style.transform = 'rotate(180deg)';
            } else {
                console.log("Menu is shown, hiding now.");
                menu.classList.remove('show');
                menu.classList.add('hide');
                icon.style.transform = 'rotate(0deg)';
            }
        });

        document.addEventListener('click', function(event) {
            var isClickInsideIcon = document.getElementById('userAccountIcon').contains(event.target);
            var isClickInsideMenu = document.getElementById('userAccountMenu').contains(event.target);

            
                if (!isClickInsideIcon && !isClickInsideMenu) {
                
                // If the click is outside the userAccountIcon and userAccountMenu, close the menu
                document.getElementById('userAccountMenu').classList.add('hide');
                document.getElementById('userAccountMenu').classList.remove('show');
                document.querySelector('.user-expand-icon').style.transform = 'rotate(0deg)';
            }
        });
        


        // Handling click events on sidebar links with submenu
        document.querySelectorAll('.sidebar-link.has-submenu').forEach(item => {
            item.addEventListener('click', function(e) {
                console.log("Submenu item clicked.");
                closeAllSubmenus();
                
                e.preventDefault();
    
                let nextElement = this.nextElementSibling;
                if (nextElement && nextElement.classList.contains('submenu')) {
                    this.classList.toggle('open');
                    nextElement.style.display = nextElement.style.display === 'block' ? 'none' : 'block';
                }
    
                e.stopPropagation();
            });
        });
    });
    

</script>
    


</body>

modules/templates/maintenance.html
{% extends "base.html" %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-12 text-center">
            <h1>Maintenance in Progress</h1>
            <p>We're sorry, but HackPlanet.EU is currently undergoing maintenance.</p>
            <p>Please check back later. We appreciate your patience!</p>
        </div>
    </div>
</div>
{% endblock %}